name: Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Projeyi indir
        uses: actions/checkout@v4

      - name: Java 17 kur
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Android SDK lisanslarını kabul et
        run: |
          yes | sdkmanager --licenses || true

      - name: Gerekli Android SDK paketlerini kur
        run: |
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-36"
          sdkmanager "build-tools;36.0.0"

      - name: ZIP'i aç
        run: |
          unzip -q YeniKoza-main.zip -d project
          echo "Proje dosyaları:"
          ls -la project/YeniKoza-main

      - name: Gradle ile APK oluştur
        working-directory: project/YeniKoza-main
        run: |
          gradle assembleDebug --no-daemon

      - name: APK'yı GitHub'a yükle
        uses: actions/upload-artifact@v4
        with:
          name: YeniKoza-APK
          path: project/YeniKoza-main/app/build/outputs/apk/debug/*.apk
